#!/bin/sh

#
# Copyright 2022 Ole Richter - University of Groningen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [ x$ACT_HOME = x ]
then
	echo "Please set the environment variable ACT_HOME to the install directory"
        exit 1
fi

if [ x$EDA_SRC = x ]
then
	export EDA_SRC=$(pwd)/src
fi

# make sure $ACT_HOME/bin is highest prio for the tests
export PATH=$ACT_HOME/bin:${PATH}


#run all avalible test in order
for test in tests/*test.sh; do
    echo 
    echo "#### $test ####"
    echo
    bash $test || exit 1
done